/**
 * Sanitizes JSON strings that may have common formatting issues,
 * especially those generated by AI models like Ollama or Gemini.
 */
export function sanitizeJsonString(jsonStr: string): string {
  if (!jsonStr) return jsonStr;

  // 1. Replace backslash followed by a non-valid JSON escape character
  // Valid JSON escape sequences are: \" \\ \/ \b \f \n \r \t \u
  let result = jsonStr.replace(/\\(?!["\\/bfnrtu])/g, '\\\\');

  // 2. Replace literal control characters (like newlines, tabs) inside JSON strings
  let inString = false;
  let isEscaped = false;
  let sanitized = '';

  for (let i = 0; i < result.length; i++) {
    const char = result[i];

    if (inString) {
      if (char === '"' && !isEscaped) {
        inString = false;
        sanitized += char;
      } else if (char === '\\' && !isEscaped) {
        isEscaped = true;
        sanitized += char;
      } else {
        isEscaped = false;
        if (char === '\n') {
          sanitized += '\\n';
        } else if (char === '\r') {
          sanitized += '\\r';
        } else if (char === '\t') {
          sanitized += '\\t';
        } else if (char.charCodeAt(0) < 32) {
          sanitized += '\\u' + char.charCodeAt(0).toString(16).padStart(4, '0');
        } else {
          sanitized += char;
        }
      }
    } else {
      if (char === '"') {
        inString = true;
      }
      sanitized += char;
    }
  }

  return sanitized;
}
